### ISSUE TITLE
Getting segfaults that shouldn't happen (I think)

### ISSUE THREAD

**Issue by DGKSK8LIFE** [markcheno/go-quote#18]
# My code: 

```
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/markcheno/go-quote"
	"github.com/markcheno/go-talib"
)

var start *string
var end *string
var stock *string

func init() {
	if os.Args[0] == "quote" {
		start = flag.String("start", "", "starting point of your stock value")
		end = flag.String("end", "", "ending point of your stock value")
		stock = flag.String("stock", "", "stock name")
		flag.Parse()
	}
}

func main() {
	spy, err := quote.NewQuoteFromYahoo(strings.ToLower(*stock), *start, *end, quote.Daily, true)
	if err != nil {
		panic(err)
	}
	rsi2 := talib.Rsi(spy.Close, 2)
	fmt.Println(rsi2)
}
```

# My error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x652a29]

goroutine 1 [running]:
main.main()
        /home/tarekali/code/ETF-sim/main.go:25 +0x39
exit status 2
```

**Comment by markcheno** [comment]
That has nothing to do with go-quote. You have an issue with your flags.
This main works fine:
`func main() {
	spy, err := quote.NewQuoteFromYahoo(strings.ToLower("spy"), "2020-01-01", "", quote.Daily, true)
	if err != nil {
		panic(err)
	}
	fmt.Println(spy)
	rsi2 := talib.Rsi(spy.Close, 2)
	fmt.Println(rsi2)
}
`

**Comment by Alkiwi** [comment]
Hello, the problem here is your usage of flags. `os.Args[0]` is the binary name, it'll will contain the full-length path (ex: /tmp/gdk/quote). You can still parse that and only get the last part, but I wouldn't do that.

### Solution
#### CLI Usage
```sh
alki@build$ ./___go_build_dgk quote -start=<date> -end=<date> -stock=<stock>
```
 
#### Code
```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/markcheno/go-quote"
	"github.com/markcheno/go-talib"
)

var (
	start string
	end   string
	stock string
)

func init() {
	if len(os.Args) > 1 && os.Args[1] == "quote" {
		quoteArgs := flag.NewFlagSet("quote", flag.ExitOnError)

		quoteArgs.StringVar(&start, "start", "", "starting point of your stock value")
		quoteArgs.StringVar(&end, "end", "", "ending point of your stock value")
		quoteArgs.StringVar(&stock, "stock", "", "stock name")

		err := quoteArgs.Parse(os.Args[2:])
		if err != nil {
			os.Exit(1)
		}
	}
}

func main() {
	spy, err := quote.NewQuoteFromYahoo(strings.ToLower(stock), start, end, quote.Daily, true)
	if err != nil {
		log.Fatal(err.Error())
	}

	rsi2 := talib.Rsi(spy.Close, 2)
	fmt.Println(rsi2)
}
```

**Comment by DGKSK8LIFE** [comment]
Thanks but now I'm getting this error:

# Input
```
go run main.go quote -start=2016-01-01 -end=2016-01-04 -stock=tsla 
```

# Output
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/markcheno/go-talib.Rsi(0x92d4c8, 0x0, 0x0, 0x2, 0x7fff3259bff9, 0xa, 0x6eae8a)
        /home/tarekali/go/pkg/mod/github.com/markcheno/go-talib@v0.0.0-20190307022042-cd53a9264d70/talib.go:2820 +0x297
main.main()
        /home/tarekali/code/ETF-sim/main.go:41 +0x12a
exit status 2
```

**Comment by DGKSK8LIFE** [comment]
Ok my input threshold was too short. Works when I extend it. Thank you very much sir @Alkiwi

**Comment by Alkiwi** [comment]
Not enough data? spy.Close's empty. Not into stocks, can't help, but you're probably in charge of checking what the API return.
